name: ddata
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  redux_epics: ^0.10.0
  redux_persist:
  reselect:
  redux_persist_flutter:
    git:
      url: git://github.com/Cretezy/redux_persist
      ref: master
      path: packages/redux_persist_flutter
  flutter_redux_dev_tools:
  redux_dev_tools:
  shared_preferences:
  redux: ^3.0.0
  path_provider:
  rxdart: ^0.18.1
  flutter_sparkline: ^0.0.3
  charts_flutter:
  quiver: '>=2.0.0 <3.0.0'
  json_serializable:
  web_socket_channel: 1.0.7
  open_iconic_flutter:
  font_awesome_flutter:
  http:

dev_dependencies:
  build_runner:
  # flutter_test:
  #   sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true 
  ios: "Example-Icon"
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
